lib/mix/tasks/swagger.generate.ex

When using scopes, the modulenames were wrongly concatinated, because the information about the scopes were lost.

corrected module name concatination for scopes

---

lib/mix/tasks/swagger.generate.ex
lib/phoenix_swagger.ex

Why?
Because Elixir provides [List.flatten/1](https://github.com/elixir-lang/elixir/blob/64ee036509c34e097017e89fc0af3818110043d3/lib/elixir/lib/list.ex#L152) which calls to `:lists.flatten` btw.

Use Elixir List.flatten/1 instead of Erlang :lists

---

mix.exs
mix.lock

Hi, There!
This patch allows to use both 2.x and 1.5 (or higher) version of poison, which is same as the dependency of [phoenix ver 1.2.1](https://github.com/phoenixframework/phoenix/blob/aa997350f917a6437a059f265a5647cd22625219/mix.exs#L45)
Please let me know if you have any concerns.

allow both 2.x and 1.5 version of poison

---

README.md

The read me contained an example that should refer to the schema defined immediately below the swagger_model. 
Also, you need to recompile your app for the `phoenix.swagger.generate` mix task to update the `swagger.json` with your most recent schema changes.

The second swagger_model example uses the schema.

---

lib/mix/tasks/swagger.generate.ex

If you defined a `title` in swagger_info, the resulting swagger.json file contained `"info":null`.
On line 145 when the `title` was not nil, `info` would be assigned to null. 
The same thing occurred for `version` on line 148.

Use swagger_info title and version defined in mix.exs

---

lib/phoenix_swagger.ex

In Swagger, a parameter located in the `body` shouldn't have a `type` - instead, it should have a `schema` describing the data structure in that parameter. This PR adds that functionality so something like this works as intended:
```elixir
swagger_model :create do
parameter :body, :user, user_schema, :required, "User"
end
def user_schema do
%{
type: :object,
properties: %{
name: %{type: :string}
}
}
end
```

add support for body parameters with a custom schema

---

lib/mix/tasks/swagger.generate.ex

The `phoenix.swagger.generate` task only picks up routes if they are in a scope that has exactly one pipeline which is equal to `:api`. This is an issue if you have multiple api scopes (ex authenticated vs unauthenticated).

allow additional pipes

---

README.md
lib/phoenix_swagger/validator.ex
test/test_spec/swagger_test_spec_2.json
test/validator_test.exs

This patch provides additional clause for `parse_swagger_schema/1`
function to read set of swagger schemas. After reading of list of
swagger schemas, validator merges them into one.
So other behaviour of validator is the same as before.

validator: add support for multiple schemas

---

lib/mix/tasks/swagger.generate.ex

If the config is in prod environment for example and it looks like this:
(...)
http: [port: {:system, "PORT"}],
url: [host: System.get_env("URI"), port: 80],
(...)
this will generate errors like this:
** (MatchError) no match of right hand side value: [host: "localhost", port: "4123"]
lib/mix/tasks/swagger.generate.ex:119: Mix.Tasks.Phoenix.Swagger.Generate.collect_host/3
lib/mix/tasks/swagger.generate.ex:56: Mix.Tasks.Phoenix.Swagger.Generate.run/1
(mix) lib/mix/task.ex:296: Mix.Task.run_task/3
(mix) lib/mix/task.ex:328: Mix.Task.run_alias/3
(mix) lib/mix/task.ex:261: Mix.Task.run/2
(mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
This is a fix for this issue.

BUGFIX: read port/url from config (also from env if necessary)

---

lib/mix/tasks/swagger.generate.ex

If you input some directory which doesn't exist on swaggerfile generation, then it won't be created (and it doesn't throw, which is bad in my opinion too in this case - for instance in CI/CD envs)

Fix: create directory if it doesn’t exist for generated file

---

lib/phoenix_swagger/plug/validate_plug.ex
lib/phoenix_swagger/validator.ex
test/test_spec/swagger_test_spec_2.json
test/validator_test.exs

This patch provides following changes for swagger validator:
1. Validation of query parameters moved to PhoenixSwagger.Plug.Validate
plug as we can't validate them correctly with json schema.
2. Error fixed with validation of required fields of nested objects.

swagger validator reworked

---

lib/phoenix_swagger/plug/validate_plug.ex
lib/phoenix_swagger/validator.ex

The swagger specification may provide `basePath` attribute. So we
need to consider this case and strip it from request path to
validate an url.

strip swagger 'basePath' before validation

---

lib/phoenix_swagger.ex
lib/phoenix_swagger/schema.ex
test/phoenix_swagger_test.exs

Source for this PR extracted from https://github.com/everydayhero/phoenix_swagger/blob/master/lib/phoenix_swagger/schema.ex
- Defines the Schema structure reflecting http://swagger.io/specification/#schemaObject
- Serves to document the available attributes that can be used in a swagger schema
- Doctests provided for basic usage examples
- provides some functions for updating a Schema:
```elixir
schema = 
%Schema{type: :object, title: "User"}
|> Schema.description("A user with a name and phone number")
|> Schema.property(:name, :string, "Full name", required: true, maxLength: 256)
|> Schema.property(:phone_number, :string, "Phone Number", required: true)
```
This module can be used as-is, but will eventually be wrapped in a macro to improve readability:
```elixir
swagger_schema do
title …
```

Add PhoenixSwagger.Schema module

---

lib/phoenix_swagger.ex
lib/phoenix_swagger/schema.ex
test/phoenix_swagger_test.exs

Sorry about the +579 additions, it is mostly doc strings and trivial 3 line functions.
`PhoenixSwagger.swagger_schema` defines a macro that makes constructing a schema quite readable.
```elixir
swagger_schema do
title "Pet"
description "A pet in the pet store"
properties do
id :integer, "Unique identifier", required: true, format: :int64
name :string, "Pets name", required: true
tags array(:string), "Tag categories for this pet"
end
additional_properties false
end
```
- `swagger_schema` simply pipelines functions defined in the PhoenixSwagger.Schema module
- can be used anywhere a map literal would be used in current usage.
- `PhoenixSwagger.Schema.properties` macro works similarly, but inserts a function call to `PhoenixSwagger.Schema.property` in front of each expression.
- Many …

Add swagger_schema DSL macro

---

lib/phoenix_swagger.ex
lib/phoenix_swagger/path.ex
lib/phoenix_swagger/schema.ex
test/path_test.exs

This PR adds the `PhoenixSwagger.swagger_path` macro, which is similar to the existing swagger_model macro.
- swagger_path defines a function `swagger_path_<action>` which when called produces a map
that can be merged into the `paths` section of a swagger document.
- `PhoenixSwagger.Path` module defines some structs for Parameter, Response, Operation and Path
- Similar to `PhoenixSwagger.Schema`, there are some functions for manipulating the structures,
mostly for transforming a `%PathObject{}` struct through a pipeline.
- Since defining parameters very common, there is a macro for `parameters` similar to schema `properties`.
- Pagination parameter helper defaults parameter names to match [scriviner_ecto](https://github.com/drewolson/scrivener_ecto) convention
- Test file `path_test.exs` …

Add swagger path/operation DSL

---

lib/phoenix_swagger.ex
lib/phoenix_swagger/json_api.ex
test/json_api_test.exs

This adds a helper module for defining swagger schemas for [JSON:API](http://jsonapi.org) apis.
The example below shows how much boilerplate is saved by using the `PhoenixSwagger.JsonApi` module vs maintaining a raw JSON swagger file.
Example:
```elixir
use PhoenixSwagger
def swagger_definitions do
%{
UserResource: JsonApi.resource do
description "A user that may have one or more supporter pages."
attributes do
phone :string, "Users phone number"
full_name :string, "Full name"
user_updated_at :string, "Last update timestamp UTC", format: "ISO-8601"
user_created_at :string, "First created timestamp UTC"
email :string, "Email", required: true
birthday :string, "Birthday in YYYY-MM-DD format"
address Schema.ref(:Address), "Users address"
end
link :self, "The link to this user resource" …
```

Add JSON-API helpers

---

.travis.yml
mix.lock

Poison still generates a warning.

Update dependencies to reduce compile warnings on Elixir 1.4

---

lib/phoenix_swagger/plug/validate_plug.ex

A request data may contain more than one error, we should handle this
too.

handle multiple errors

---

CHANGELOG.md
lib/phoenix_swagger.ex

Fixes compilation errors caused by `PhoenixSwagger.JsonApi` module not required before using the JsonApi.resource macro.
The symptom is a for code such as:
```elixir
def swagger_definitions do
%{
UserResource: JsonApi.resource do
title "UserResource"
description "A user with a profile page"
attributes do
given_name :string, "The user's given name"
email :string, "The user's email"
end
end
}
end
```
```
== Compilation error on file lib/user_controller.ex ==
** (CompileError) lib/user_controller.ex:22: undefined function title/1
(stdlib) lists.erl:1338: :lists.foreach/2
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```
Not sure why this was working in the unit tests, but not working from a real project?

Change alias to require in __using__ macro

---

lib/phoenix_swagger/path.ex
test/json_api_test.exs
test/path_test.exs

Add support for `examples` and `headers` keyword options in `response` (http://swagger.io/specification/#responseObject)
```elixir
swagger_path :index do
get "/api/v1/users"
produces "application/json"
response 200, "OK", :Users, example: %{id: 1, name: "Joe", email: "joe@gmail.com"}
end
```

Support response examples in path DSL

---

CHANGELOG.md
lib/phoenix_swagger/path.ex
test/path_test.exs

#53 introduced a regression where any time `response` was used without a preceding `produces`, a `FunctionClauseError` would happen.
This PR adds a test case and fixes the bug by adding another function clause on `expand_response_example` to handle this case.

Fix response without produces

---

CHANGELOG.md
lib/phoenix_swagger/json_api.ex
lib/phoenix_swagger/schema.ex
test/json_api_test.exs

The JSON schema standard allows for multiple types assigned to a single type: https://spacetelescope.github.io/understanding-json-schema/reference/type.html
This adds the capability to have a list.
I've also added the Schema doctests as they weren't being run.

Support multiple types for schema properties

---

CHANGELOG.md
lib/mix/tasks/swagger.generate.ex

Phoenix routes to a controller always have the controller action as the opts, eg :index
However Phoenix router can route to any plug, which can have any opts, often a keyword list.
This change causes any route without a single atom opts field to be ignored.

Fix #58 - Ignore routes with keyword list options

---

lib/mix/tasks/swagger.generate.ex

I need to have the url for my endpoint in swagger be different than the url being generated by the Phoenix router.
I couldn't identify any reason we needed this match. If we remove the match, then we can specify any url when defining a swagger path.
``` elixir
swagger_path :index do
get "/anything/you_want/widgets"
```

Remove match to allow custom swagger paths

---

lib/mix/tasks/swagger.generate.ex

In an umbrella app it's expected that not all applications will have Endpoints, this is a small PR to check if an application has a configured Endpoint before attempting to load it's router. 
In a sample umbrella with three applications, one of which uses phoenix:
Previous behavior:
``` 
> mix phoenix.swagger.generate
** (MatchError) no match of right hand side value: {:error, :nofile}
lib/mix/tasks/swagger.generate.ex:68: Mix.Tasks.Phoenix.Swagger.Generate.load_router/1
lib/mix/tasks/swagger.generate.ex:43: Mix.Tasks.Phoenix.Swagger.Generate.run/1
(mix) lib/mix/task.ex:294: Mix.Task.run_task/3
(mix) lib/mix/project.ex:312: Mix.Project.in_project/4
(elixir) lib/file.ex:1162: File.cd!/2
(mix) lib/mix/task.ex:394: anonymous fn/4 in Mix.Task.recur/1
(elixir) lib/enum.ex:1755: …
```

Skip applications with no Endpoints (Improves Umbrella support)

---

CHANGELOG.md
README.md
examples/simple/priv/static/swagger.json
examples/simple/web/controllers/user_controller.ex
lib/phoenix_swagger/schema.ex

This PR adds support for supplying an example with each schema definition.
A single schema example is supported by the swagger spec: http://swagger.io/specification/#schemaObject
When given, swagger-ui will populate the `example value` text area with this example, making it easier to make POST requests from swagger-ui.

Schema examples

---

CHANGELOG.md
lib/mix/tasks/swagger.generate.ex

In the swagger spec it states that
```
If the host is not included, the host serving the documentation is to be used (including the port)
```
This PR will change the host assignment to match the above spec where a host will not be provided in the resulting swagger.json if a URL is not provided.

Do not assign a host if one has not been provided

---

CHANGELOG.md
lib/phoenix_swagger/schema.ex

Adds the `discriminator` field to the `PhoenixSwagger.Schema` struct, as described in the swagger spec section [composition-and-inheritance](http://swagger.io/specification/#composition-and-inheritance--polymorphism--83)
As an example of usage, the "Pet" schema could be a base schema, extended by "Cat" and "Dog", using the "petType" field as discriminator:
```elixir
def swagger_definitions() do
%{
Pet: swagger_schema do
discriminator "petType"
properties do
name :string, "Pets name", required: true
petType :string, "Concrete pet type", required: true
end
end
Cat: swagger_schema do
description "A representation of a cat",
all_of [
Schema.ref(:Pet),
swagger_schema do
type :object
properties do
huntingSkill :string, "The measured skill for hunting",  required: true, default: "lazy",
enum: …
```

Add discriminator schema field for polymorphic schemas

---

CHANGELOG.md
README.md
lib/phoenix_swagger.ex
lib/phoenix_swagger/json_api.ex
lib/phoenix_swagger/path.ex
lib/phoenix_swagger/schema.ex
test/path_test.exs

This PR adds the ability to declare a `property` schema inline, where previously `Schema.ref` would have been required to reference a named schema.
A new macro `Schema.new` allows a `Schema` struct to be built using the `Schema` DSL, and passed anywhere that is expecting a `Schema` struct (parameters, properties, responses, etc..).
I also found that many macros that accepted a `do-end` block didn't work when given only a single expression, so I've updated them to handle that case too.
Example using inline property schemas, the `preferences` property doesn't need to be defined separately:
```elixir
swagger_schema do
title "User"
description "A user of the application"
properties do
name :string, "Users name", required: true
id :string, "Unique identifier", required: true
address :string, …
```

Inline property schemas

---

.gitattributes

This should stop github from reporting the repo as a javascript repo.
From: https://github.com/github/linguist#overrides
> Use the linguist-vendored attribute to vendor or un-vendor paths.
```
$ cat .gitattributes
special-vendored-path/* linguist-vendored
jquery.js linguist-vendored=false
```

Configure github to treat priv/static as vendored code

---

README.md

This patch updates description of usage of phoenix_swagger validator.
As we have no `PhoenixSwagger.Validator.Supervisor` anymore, let's
remove it from description.

update description of usage of validator

---

README.md
lib/mix/tasks/swagger.generate.ex

It can be confusing when forgetting to run `mix compile` before `mix phoenix.swagger.generate` produces a swagger file that does not match the code.
This change automatically runs the "compile" mix task from the phoenix.swagger.generate task.

Compile sources before generating swagger

---

README.md

This has confused a few people (#80, #81) so update the docs to clarify.

Note trailing slash is required for swagger-ui

---

CHANGELOG.md
README.md
lib/phoenix_swagger/plug/swaggerui.ex

With this change, a request to any of `/api/swagger`, `/api/swagger/` or `/api/swagger/index.html` should properly show the swagger ui.
Should resolve #86
Also related to #81 and #80
The strategy is to use a redirect from `/api/swagger` or `/api/swagger/` to `/api/swagger/index.html`.
Then when rendering the `index.html` EEx template, replace `index.html` with the `swagger.json` filename to get the swagger spec.
I've tested using the example app in the repo.
log output when requesting `/index.html`:
```
MACBOOK121:simple michael.buhot$ mix phoenix.server
[info] Running Simple.Endpoint with Cowboy using http://localhost:4000
[info] GET /api/swagger/index.html
[info] Sent 200 in 17ms
```

Swaggerui redirect / to /index.html

---

CHANGELOG.md
lib/phoenix_swagger/plug/swaggerui.ex

This causes all the tags to be expanded, listing the available operations.
We could make this configurable, but I think this is a better default and is consistent with the new swaggerui 3.0 layout (http://petstore.swagger.io) 
Resolves #77 
From https://github.com/swagger-api/swagger-ui/tree/2.x#parameters
Parameter Name | Description
-----------------|-------------
docExpansion | Controls how the API listing is displayed. It can be set to 'none' (default), 'list' (shows operations for each resource), or 'full' (fully expanded: shows operations and their details).

Set swagger-ui docExpansion expansion to "list"

---

CHANGELOG.md
README.md
examples/simple/config/config.exs
examples/simple/config/prod.exs
lib/mix/tasks/swagger.generate.ex
mix.exs

There are two main changes in this PR:
1. `phx.swagger.generate` will use "localhost:4000" for default hostname and port if one is not provided.
2. When host/port are configured to use {:system, "ENV_VAR"} tuples, the swagger host is not included.
This allows a new phoenix project to work with phoenix_swagger without having to change/remove any configuration settings in dev config.
It also allows for deploying swagger-ui to testing environments with dynamic host settings.
Resolves #91 
Resolves #93

Default host / port and handle dynamic url config

---

CHANGELOG.md
README.md
lib/phoenix_swagger/plug/swaggerui.ex
mix.exs

Path to a swagger specification file is calculated during compilation
based on path of the application directory. Such path can differ from
the same path in runtime.

fix path to swagger specification file in UI plug

---

README.md
lib/phoenix_swagger/plug/swaggerui.ex

No longer requires passing the empty `opts: []` list when not overriding
the `disable_validator` flag.

SwaggerUI plug options combined into single list

---

CHANGELOG.md
README.md
lib/mix/tasks/swagger.generate.ex

I have an app which uses Phoenix 1.3 without having fully adopted its conventions. This means that its Endpoint does not have a `Web` prefix and so Phoenix Swagger does not work right away.
I have made a couple changes essentially allowing the module name for Endpoint to be passed in from the Mix task, when regenerating a Swagger document.
In addition there is another small fix for when not all modules can be reached when enumerating routes from within a Router. I have found that when prototyping a system it is beneficial to have all the routes laid out first before implementing the controllers. It is still beneficial to have Swagger documents generated from time to time without the routes being fully implemented.

Custom Endpoint Support

---

examples/simple/lib/simple/application.ex
examples/simple/lib/simple/web/router.ex
examples/simple/mix.exs
examples/simple/test/controllers/user_controller_test.exs
lib/phoenix_swagger/plug/validate_plug.ex
lib/phoenix_swagger/validator.ex

This PR started by trying to add the Validator plug to the example app.
Along the way I needed to add a couple of features, and took the opportunity to refactor the code a bit. I've tried to break it up to allow reviewing each commit separately.
- `examples/simple/lib/web/router` adds `PhoenixSwagger.Plug.Validate` to the `api` pipeline
- `PhoenixSwagger.Plug.Validate` accepts a `:validation_failed_status` option, defaults to 400 but can be used to produce 422 responses when validation fails
- `PhoenixSwagger.Plug.Validate` works when `basePath` is missing from swagger spec. Was previously throwing an `ArgumentError` trying to `String.split` the `basePath`.
- Error responses from `PhoenixSwagger.Plug.Validate` plug set the response content type to `application/json`. Without this the …

Add Validator plug to example project

---

mix.exs
mix.lock

The version of poison in this project is far behind the latest version. Due to some other dependencies I need phoenix_swagger to support poison 3.1 as well.

Allow poison 3.1

---

README.md
docs/reusing-swagger-parameters.md
mix.exs

I've added a wiki page with some details on how to reuse parameters across actions/controllers, following @mbuhot's great help with #115. 
[Reusing swagger parameters](https://github.com/xerions/phoenix_swagger/wiki/Reusing-swagger-parameters)
I thought it might be best to put this in the Wiki and link to it from the README so it doesn't clutter things up too much.

Adding README link to Reusing Swagger Parameters wiki page

---

CHANGELOG.md
lib/mix/tasks/swagger.generate.ex
mix.exs

* Phoenix 1.3 namespaces now supported with phx.swagger.generate.
* Version bump to 0.6.5.
* Fixes Issue 117.
Between Phoenix 1.3 RCs and the Phoenix 1.3 release, a
modification was made to the Web namespace: instead of
the namespace being {ProjectName}.Web, it was changed to
{ProjectName}Web. The namespace for the router and endpoint
now correctly defaults to the correct 1.3 namespace.
Phoenix 1.2 applications are still supported by providing the
router and endpoint to phx.swagger.generate using the -r and -e
switches.

Implement Phoenix 1.3 Namespacing Recognition

---

lib/phoenix_swagger/json_api.ex
test/json_api_test.exs

JSON API allows relationships to be arrays for "has-many". This patch allows a `:type` option to be passed to the `relationship` function so that the relationship can be set to `:array` (currently it's hardcoded to `:object`).

Allow relationships to be array

---

lib/phoenix_swagger/json_api.ex
test/json_api_test.exs

Fixes #133
* Remove "null" from type of JSONAPI prev/next because SwaggerUI does not understand that type.

Remove "null" from type of JSONAPI prev/next

---

docs/reusing-swagger-parameters.md

parameter function takes 4th arguments which describe type of the parameter.

correct arguments of parameter function in docs

---

CHANGELOG.md
lib/phoenix_swagger/plug/validate_plug.ex
test/plug/validate_test.exs
test/test_spec/swagger_jsonapi_test_spec.json

Fixes #137 
* Tests for nested and non-nested required parameters for `PhoenixSwagger.Plug.Validate`.
* Decode parameter names using `Plug.Conn.Query.decode` and walk `conn.params` to find the nested param as `conn.params` is already nested while `parameter["name"]` is not when received by `PhoenixSwagger.Plug.Validate.validate_query_params/2`.

Get nested names for query parameter validations

---

CHANGELOG.md
README.md
examples/simple/config/config.exs
lib/mix/tasks/swagger.generate.ex
mix.exs

Following from #130, this change should allow `mix phx.swagger.generate` to run from anywhere in an umbrella project and output the swagger file/s as expected.
Remove command line options and default values for specifying `Router` and `Endpoint`.
Each project that generates swagger files must declare a configuration such as:
```elixir
config :my_project, :phoenix_swagger,
swagger_files: %{
"priv/static/swagger.json" => [router: Some.Router, endpoint: Some.Endpoint]
}
```
`:endpoint` is optional in the configuration.
Multiple swagger files can be created, supporting the scenarios when a single project contains multiple `Router` modules or even multiple `Endpoint` listening on different ports.
- Is there a cleaner way to express the configuration that still handles the multiple …

Use explicit configuration for swagger file generation

---

CHANGELOG.md
examples/simple/lib/simple_web/controllers/user_controller.ex
lib/mix/tasks/swagger.generate.ex
lib/phoenix_swagger.ex
lib/phoenix_swagger/path.ex
test/path_test.exs

Closes #145 
This PR allows the HTTP verb and path to be inferred from the phoenix router.
Earlier versions of phoenix_swagger allowed this, but it was changed to allow overriding it from the controller.
The new version passes the verb and path from the mix task in to the `swagger_path_***` function for use as default values.
/cc @pablobcb

Allow verb and path to be inferred from router

---

lib/phoenix_swagger/plug/swaggerui.ex

Change format style in code. Remove warning returned in `elixir 1.6.1` version (with `format`).
```elixir
==> phoenix_swagger
Compiling 9 files (.ex)
warning: outdented heredoc line. The contents inside the heredoc should be indented at the same level as the closing """. The following is forbidden:
def text do
"""
contents
"""
end
Instead make sure the contents are indented as much as the heredoc closing:
def text do
"""
contents
"""
end
The current heredoc line is indented too little
lib/phoenix_swagger/plug/swaggerui.ex:128
```
Now compilation without this note.

Elixir 1.6 format style

---

lib/phoenix_swagger/schema.ex
test/path_test.exs

From https://swagger.io/specification/#schemaObject under "Fixed fields":
> Allows sending a null value for the defined schema. Default value is false.

add nullable as a property

---

lib/phoenix_swagger/conn_validator.ex

As `PhoenixSwagger.ConnValidator` module doc described
```
* `{:error, [{message, path}], path}` if more than one validation error has been detected
```
Returns multiple errors if multiple validation error detected.

Returns multiple validation errors

---

CHANGELOG.md
lib/phoenix_swagger/plug/swaggerui.ex

We recently saw a crash when someone tried to POST to our Swagger file, and nothing matched.
I could also be convinced that `404 Not Found` is the right thing to return in this case.

send 405 Method Not Allowed for other methods

---

CHANGELOG.md
lib/phoenix_swagger/json_api.ex
test/json_api_test.exs

This PR adds the missing fields `type` and `id` to the included array of a single JSON-Api Response, acording to your comment in the PR #182 . This should also fix the issue with `swagger-codegen` and invalid/unkown objects in a array.
https://github.com/xerions/phoenix_swagger/pull/182#pullrequestreview-121329948

Adds type and id to the `included` array of a single jsonapi object

---

docs/getting-started.md
examples/simple/mix.exs

`:phoenix_swagger` compiler must be append at the end of `:compilers` list to avoid compilation issues.
* update documentation
* update sample `mix.exs`

update documentation and example

---

lib/phoenix_swagger/conn_validator.ex
test/test_spec/swagger_test_spec_2.json
test/validate_plug_test.exs

Added simple validation for:
- query enum params
- query array params including enum as well (comma separated) 
Note: previously using such query params would lead to Internal Server Error 
"(FunctionClauseError) no function clause matching in ConnValidator.validate_query_params/1", 
though swagger schema was valid and successfully generated

Query array/enum parrameters  validation

---

.travis.yml
mix.exs

__Changes__
* Add `Elixir-1.7.4` to Travis CI test matrix
__Why?__
We should ensure correct flow in latest Elixir version.
cc. @mbuhot

Update Travis CI matrix and set Elixir 1.6 as min. in PhoenixSwagger

---

docs/getting-started.md

In pull request https://github.com/xerions/phoenix_swagger/pull/215 we changed minimal version of Elixir language. I missed this information in Docs - and now decided to update it.
cc. @mbuhot

Update Docs in project - update minimal version of Elixir

---

lib/mix/tasks/swagger.generate.ex

This is at least a partial fix for the change in `Phoenix.Router.Route`
Fixes #229

Add support for Phoenix > 1.4.6

---

lib/phoenix_swagger/conn_validator.ex
test/test_spec/swagger_test_spec_3.json
test/validate_plug_test.exs

Ensure that a route like `/pets/cats` is matched before `/pets/{id}`. Currently, this overlapping route behaviour is not always handled correctly (depends on the default sort order).

Fix bug where templated routes are sometimes matched before specific routes

---

lib/phoenix_swagger/plug/swaggerui.ex

swagerUI plug may handle requests for non exists spec files. In this
case it returns 404 and `not found` text. This commits adds ability
to send 404 json response if Accept header is set to `application/json`
to make happy applications that wait for a json response.

add possibility to return json 404 error from swagerUI plug

---

lib/mix/tasks/swagger.generate.ex

It can be hard to debug when phoenix_swagger is misconfigured and it fails silently.
This change outputs a warning like:
```
20:15:31.855 [warn]  No swagger configuration found. Ensure phoenix_swagger is configured, eg:
config :promo, :phoenix_swagger,
swagger_files: %{
...
}
```
The warning does not apply when recursing in umbrella applications,
only when running the compiler / mix task directly on a mix project.

Warn when no phoenix_swagger config found

---

lib/phoenix_swagger/test/schema_test.ex
mix.exs
mix.lock
test/validator_test.exs

There are some breaking changes in the newer version of ExJsonSchema.
Particularly the `ExJsonSchema.Validator.validate/4` function no longer exists, but has been replaced with `ExJsonSchema.Validator.validate_fragment/3` which performs a similar function.

Update ex_json_schema to 0.6

---

lib/phoenix_swagger/plug/swaggerui.ex

Closes #252 
Would like to be able to specify a custom swagger ui config url. 
This can be done using the `configUrl` config parameter: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/.

Allow swagger ui config url to be customized

---

.gitignore
lib/phoenix_swagger/plug/swaggerui.ex

This allows a dev to specify a swagger configuration object that is used by the SwaggerUI JS object during construction. This allows you to have granular control of swagger and control the configuration per environment without having to rely on an external url or yaml file.
As an example I needed to set `oauth2RedirectUrl` depending on the env to integrate our oauth server.
The SwaggerUI plug has been updated with the new (optional) `config_object` option. It expects a `map` with any key/val that is supported by swagger. https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
Also the template was modified to place the config object in a variable - then we iterate on the config_object template var to set all the given options.
I didn't see any tests for this plug so I …

[MINOR] Support SwaggerUI config object injection

---

lib/phoenix_swagger/schema.ex

now its possible to do:
tunnel-ip(Schema.ref(:IpAddressWithPrefix), "local tunnel ip, BGP local IP", required: true)
following AST is generate for above property
{:-, [line: 156],
[
{:tunnel, [line: 156], nil},
{:ip, [line: 156],
[
{{:., [line: 156],
[
{:__aliases__, [counter: {******r, 53}, line: 156],
[:Schema]},
:ref
]}, [line: 156], [:IpAddressWithPrefix]},
"local tunnel ip, BGP local IP",
[required: true]
]}
]}

added support for having property name with "-" in the name e.g

---

lib/phoenix_swagger/test/schema_test.ex
lib/phoenix_swagger/validator.ex
test/test_spec/swagger_test_spec_2.json
test/validator_test.exs

@0xAX
This is like https://github.com/xerions/phoenix_swagger/pull/267, but works for `$ref`
I used the answer here to guide my solution:
https://stackoverflow.com/questions/23729973/how-to-specify-a-property-as-null-or-a-reference
I'm not sure if the x-nullable extension should allow this, but it's not part of the swagger spec so hard to have a definitive answer.

allow nullable refs

---

priv/static/swagger-initializer.js

Update the `url` passed to swagger-ui, so that it will use the default `swagger.json` generated by `mix phx.swagger.generate`.
closes #292

Correct link to swagger JSON file in swagger-ui

---

CHANGELOG.md
mix.exs

Changelog:
* swagger-ui-dist updated to 5.2.0.
* Fix validation of boolean properties. Thanks to @charl3sj
* Allow nullable `$ref`. Thanks to @ericsullivan
* Nullable fields validated correctly. Thanks to @ericsullivan
* Add support SwaggerUI config object injection. Thanks to @heroinbob
* Add support to have property names with `-` symbol. Thanks to @fahadnaeemkhan
* Documentation improvements. Thanks to @kianmeng and @leticiapenha
* Use Elixir formatter. Thanks to @naps62
* Remove ex_json_schema from startup. Thanks to @lukaszsamson
* Update dependencies and phoenix_swagger itself for Elixir >= 1.16.0

phoenix_swagger 0.8.4
