xerions/phoenix_swagger

- mix.exs
> Bump elixir version to 1.2

- lib/mix/tasks/swagger.generate.ex
- lib/phoenix_swagger.ex
- test/phoenix_swagger_test.exs
> Add Tags based on sohjiro PR

- mix.exs
- test/phoenix_swagger_test.exs
> fix warning about missing parentheses

- lib/phoenix_swagger/plug/validate_plug.ex
Also use `Poison.encode!` instead of `Poisone.encode`
> second error for send_resp shoud be encoded json

- README.md
> add a note about phoenix_swagger in application list

- README.md
- lib/mix/tasks/swagger.generate.ex
- mix.exs
I wanted to use `phoenix_swagger` with a 1.3 project, so I made the changes to get it working.  This might not be how you want to approach supporting 1.3, but I figured I'd at least PR my changes and let you decide if you want to merge or not.
Thanks!
> Update to support Phoenix 1.3

- CHANGELOG.md
- README.md
- lib/phoenix_swagger/plug/swaggerui.ex
In other way, it may cause problems when UI is a private service.
> Disable validation of swagger-ui by default

- README.md
> update small example in readme

- CHANGELOG.md
- lib/phoenix_swagger/path.ex
Enable security by each endpoint
> security section

- CHANGELOG.md
- README.md
Changelog entry and README updated for #122
> Update changelog for has_many json-schema relationships

- README.md
Just something I didn't really understand how to do. Thanks for an awesome project! 💟
> Add example for setting tags descriptions to README

- CHANGELOG.md
- lib/phoenix_swagger/json_api.ex
- lib/phoenix_swagger/schema.ex
- lib/phoenix_swagger/test/schema_test.ex
- mix.exs
- mix.lock
> Nullable jsonapi relationships

- examples/simple/lib/simple_web/controllers/user_controller.ex
- examples/simple/priv/static/swagger.json
- lib/phoenix_swagger/path.ex
Added deprecated function in `PhoenixSwagger.Path`.
> Added deprecated 

- lib/mix/tasks/swagger.generate.ex
Compilation is done like in route task from the phoenix repo: https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phx.routes.ex#L30
> Fix compilation error of the swagger task #176

- docs/getting-started.md
> Added note about basePath in swagger spec

- examples/simple/.formatter.exs
- examples/simple/config/config.exs
- examples/simple/lib/simple/accounts/user.ex
- examples/simple/lib/simple/application.ex
- examples/simple/lib/simple_web/channels/user_socket.ex
- examples/simple/lib/simple_web/controllers/user_controller.ex
- examples/simple/lib/simple_web/endpoint.ex
- examples/simple/lib/simple_web/router.ex
- examples/simple/lib/simple_web/views/error_view.ex
- examples/simple/lib/simple_web/views/user_view.ex
- examples/simple/mix.exs
- examples/simple/test/simple_web/controllers/user_controller_test.exs
- examples/simple/test/simple_web/views/error_view_test.exs
- examples/simple/test/test_helper.exs
Update application after bump Elixir version (#215)
cc. @mbuhot
> Update simple example application

- lib/phoenix_swagger/plug/swaggerui.ex
This PR adds sorting to both tags and operations within those tags to make it easier to find the endpoint that you're looking for.
> Add sorting to tags and methods

- lib/phoenix_swagger/plug/swaggerui.ex
> Use PhoenixSwagger.json_library in swagger ui plug

- docs/getting-started.md
Ability to configure json library
> Update getting-started.md config :json_library

- lib/phoenix_swagger/conn_validator.ex
> Fix broken param parsing caused from Plug 1.11.0

- mix.exs
Fixes https://github.com/xerions/phoenix_swagger/issues/260
> Do not try to start ex_json_schema
